name: Tester
description: 'If a Layer tester in a Dockerfile exists, the action will set up docker buildx for the tester Layer and runs the tests'

inputs:
  PAT:  
    description: 'PAT from repo'
    required: true
  repository:
    description: 'github repository'
    required: true

outputs:
  tester:
    description: "outcome of the tester"
    value: ${{ steps.tester.outcome }}
  testrunner:
    description: "outcome of the testrunner"
    value: steps.testrunner.outcome


runs:
  using: 'composite'
  steps:
  - name: Set up docker buildx for tester
    env:
      PAT: ${{ inputs.PAT }}
    id: tester
    continue-on-error: true
    uses: docker/build-push-action@v3
    with:
      context: .
      file: ./Dockerfile
      push: true
      target: test
      tags: ghcr.io/${{ inputs.repository }}:test
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: |
       ${{ env.PAT }}

  - name: Test
    id: testrunner
    if: steps.tester.outcome == 'success'
    run: |
      docker run --rm ghcr.io/${{ inputs.repository }}:test 
    shell: bash
