name: Set up docker buildx for tester runs test
description: 'If a Layer tester exists in Dockerfile the action will set up docker buildx for the tester Layer and runs the tests'
runs:

  using: 'composite'
  steps:
  - name: Set up docker buildx for tester
    id: tester
    continue-on-error: true
    uses: docker/build-push-action@v3
    with:
      context: .
      file: ./Dockerfile
      push: true
      target: test
      tags: ghcr.io/${{ github.repository }}:test
    # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: |
        PAT=${{ secrets.PAT }}

  - name: Test
    id: testrunner
    if: steps.tester.outcome == 'success'
    run: |
      docker run --rm ghcr.io/${{ github.repository }}:test
    shell: bash

  - name: Set output
    id: set-output
    run: |
      echo "tester=steps.tester.outcome >> $GITHUB_OUTPUT
      echo "tesrunner=steps.testrunner.outcome >> $GITHUB_OUTPUT
    shell: bash

