name: Tester
description: 'If a layer tester in a Dockerfile exists, the action will set up docker buildx for the tester Layer and runs the tests'

inputs:
  TESTING_WITH_DB:
    description: 'if set to true, testcontainer will be created and tests will be run in DB'
    required: false
    default: 'false'
  ACTION_ENABLE_TESTING:
    description: 'if set to true, testcontainer will be created and tests will be run'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Display inputs
    id: display_inputs
    run: |
      echo "${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Display inputs outcome
    run: |
      echo "${{steps.display_inputs.outcome}}"
    shell: bash
    
  - name: Test if both inputs are false
    if: (${{inputs.ACTION_ENABLE_TESTING}} == 'false' && ${{inputs.TESTING_WITH_DB}} == 'false')
    run: |
      echo "if ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test if one input is true
    if: (inputs.ACTION_ENABLE_TESTING == 'true' || inputs.TESTING_WITH_DB == 'true') && steps.display_inputs.outcome == 'Success'
    run: |
      echo "if ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash