name: Tester
description: 'If a layer tester in a Dockerfile exists, the action will set up docker buildx for the tester Layer and runs the tests'

inputs:
  DB_TESTDATA_FILEPATH:
    description: 'path to the testdata file'
    required: false
    default: 'false'
  ACTION_ENABLE_TESTING:
    description: 'if set to true, testcontainer will be created and tests will be run'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Display inputs
    run: |
      echo ${{inputs.ACTION_ENABLE_TESTING}} 
      echo ${{inputs.TESTING_WITH_DB}}
    shell: bash
    
  - name: Test if 
    if: ({{inputs.ACTION_ENABLE_TESTING}} == 'false' && {{inputs.TESTING_WITH_DB}} == 'false')
    run: |
      echo "if ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash
