name: Tester
description: 'If a layer tester in a Dockerfile exists, the action will set up docker buildx for the tester Layer and runs the tests'

inputs:
  TESTING_WITH_DB:
    description: 'if set to true, testcontainer will be created and tests will be run in DB'
    required: false
    default: 'false'
  ACTION_ENABLE_TESTING:
    description: 'if set to true, testcontainer will be created and tests will be run'
    required: false
    default: 'false'

# env:
#   ACTION_ENABLE_TESTING: ${{ inputs.ACTION_ENABLE_TESTING }}
#   TESTING_WITH_DB: ${{ inputs.TESTING_WITH_DB }}

runs:
  using: 'composite'
  steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Display inputs
    id: display_inputs
    run: |
      echo "${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Display inputs outcome
    run: |
      echo "${{steps.display_inputs.outcome}}"
    shell: bash
    
  - name: Test if both inputs are false 1.1
    if: ${{inputs.TESTING_WITH_DB == 'false' && inputs.ACTION_ENABLE_TESTING == 'false'}}
    run: |
      echo "1.1 if both false ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test if both inputs are false 1.2
    if:  inputs.TESTING_WITH_DB == 'false' && inputs.ACTION_ENABLE_TESTING == 'false'
    run: |
      echo "1.1 if both false ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test if one input is true
    if: (inputs.ACTION_ENABLE_TESTING == 'true' || inputs.TESTING_WITH_DB == 'true') && steps.display_inputs.outcome == 'Success'
    run: |
      echo "2 if one true ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test fromJson
    run: |
      echo "${{ fromJSON(inputs.ACTION_ENABLE_TESTING) }} ${{ fromJSON(inputs.TESTING_WITH_DB) }}"
    shell: bash

  - name: Test fromJson outcome false flase
    if: ${{ fromJSON(inputs.ACTION_ENABLE_TESTING) == 'false' && fromJSON(inputs.TESTING_WITH_DB) == 'false' }}
    run: |
      echo "3.1 if both false ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test fromJson outcome false flase
    if: ${{ fromJSON(inputs.ACTION_ENABLE_TESTING) && fromJSON(inputs.TESTING_WITH_DB) }}
    run: |
      echo "3.2 if both false ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test fromJson outcome false true
    if: ${{ fromJSON(inputs.ACTION_ENABLE_TESTING) == 'false' && fromJSON(inputs.TESTING_WITH_DB) == 'true' }}
    run: |
      echo "4 if fasle true ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test fromJson outcome true flase
    if: ${{ fromJSON(inputs.ACTION_ENABLE_TESTING) == 'true' && fromJSON(inputs.TESTING_WITH_DB) == 'false' }}
    run: |
      echo "5.1 if true false ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test fromJson outcome true flase
    if: ${{ fromJSON(inputs.ACTION_ENABLE_TESTING) || fromJSON(inputs.TESTING_WITH_DB) }}
    run: |
      echo "5.2 if true false ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash

  - name: Test fromJson outcome true true
    if: ${{ fromJSON(inputs.ACTION_ENABLE_TESTING) == 'true' && fromJSON(inputs.TESTING_WITH_DB) == 'true' }}
    run: |
      echo "6 if true true ${{inputs.ACTION_ENABLE_TESTING}} ${{inputs.TESTING_WITH_DB}}"
    shell: bash
