name: Set up docker buildx for tester runs test
description: 'If a Layer tester exists in Dockerfile the action will set up docker buildx for the tester Layer and runs the tests'

inputs:
  PAT:  # id of input
    description: 'PAT from repo'
    required: true
outputs:
  tester:
    description: "outcome of the tester"
    value: ${{ steps.tester.outcome }}
  testrunner:
    description: "outcome of the testrunner"
    value: steps.testrunner.outcome


runs:
  using: 'composite'
  steps:
  - name: Set up docker buildx for tester
    id: tester
    continue-on-error: true
    uses: docker/build-push-action@v3
    with:
      context: .
      file: ./Dockerfile
      push: true
      target: test
      tags: ghcr.io/${{ github.repository }}:test
      cache-from: type=gha
      cache-to: type=gha,mode=max
      build-args: |
       ${{ inputs.PAT }}
        
  - name: Test
    id: testrunner
    if: steps.tester.outcome == 'success'
    run: |
      docker run --rm ghcr.io/${{ github.repository }}:test 
    shell: bash

  - name: Set output
    id: set-output
    run: |
      echo "tester=steps.tester.outcome >> $GITHUB_OUTPUT
      echo "tesrunner=steps.testrunner.outcome >> $GITHUB_OUTPUT
    shell: bash 
